set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_VERSION 26.2)
set(CMAKE_SYSTEM_PROCESSOR arm64)

set(MBENCH_IOS_TRIPLE "arm64-apple-ios$ENV{MBENCH_IOS_MIN}")

set(CMAKE_OSX_SYSROOT "$ENV{MBENCH_IOS_SDKROOT}" CACHE PATH "")
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "")

set(CMAKE_C_COMPILER   "$ENV{MBENCH_IOS_TOOLBIN}/clang")
set(CMAKE_CXX_COMPILER "$ENV{MBENCH_IOS_TOOLBIN}/clang++")
set(CMAKE_ASM_COMPILER "$ENV{MBENCH_IOS_TOOLBIN}/clang")
set(CMAKE_AR           "$ENV{MBENCH_IOS_TOOLBIN}/llvm-ar"     CACHE FILEPATH "")
set(CMAKE_RANLIB       "$ENV{MBENCH_IOS_TOOLBIN}/llvm-ranlib" CACHE FILEPATH "")

set(CMAKE_C_COMPILER_TARGET   ${MBENCH_IOS_TRIPLE})
set(CMAKE_CXX_COMPILER_TARGET ${MBENCH_IOS_TRIPLE})
set(CMAKE_ASM_COMPILER_TARGET ${MBENCH_IOS_TRIPLE})

set(CMAKE_C_FLAGS_INIT   "-target ${MBENCH_IOS_TRIPLE} -isysroot $ENV{MBENCH_IOS_SDKROOT}")
set(CMAKE_CXX_FLAGS_INIT "-target ${MBENCH_IOS_TRIPLE} -isysroot $ENV{MBENCH_IOS_SDKROOT}")
set(CMAKE_ASM_FLAGS_INIT "-target ${MBENCH_IOS_TRIPLE} -isysroot $ENV{MBENCH_IOS_SDKROOT}")

set(CMAKE_EXE_LINKER_FLAGS_INIT    "-target ${MBENCH_IOS_TRIPLE} -isysroot $ENV{MBENCH_IOS_SDKROOT} --ld-path=$ENV{MBENCH_IOS_TOOLBIN}/ld64.lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-target ${MBENCH_IOS_TRIPLE} -isysroot $ENV{MBENCH_IOS_SDKROOT} --ld-path=$ENV{MBENCH_IOS_TOOLBIN}/ld64.lld")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH "$ENV{MBENCH_IOS_SDKROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_CREATE_STATIC_LIBRARY   "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_CXX_CREATE_STATIC_LIBRARY "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_ASM_CREATE_STATIC_LIBRARY "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>")
